spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2database/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # System.out.print
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # log
    org.hibernate.type: trace